sistemaInventario/Controllers/CategoriasController.cs
using sistemaInventario.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sistemaInventario.Controllers
{
    public class CategoriasController : Controller
    {
        private db_inventarioEntities db = new db_inventarioEntities();
        //crear datos
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Categoria categoria)
        {
            db.Categoria.Add(categoria);
            db.SaveChanges();
            return View();
        }
        //listar los datos
        public ActionResult Index()
        {
            var categoria = db.Categoria.ToList();
            return View(categoria);
        }
        //editar los datos
        public ActionResult Edit(int? id) // ? permite que el entero sea nulo 
        {
            if (id != null)
            {
                //select * from Categoria Where id_categoria = 1
                var categoria = db.Categoria.Find(id);
                if (categoria != null)
                {
                    return View(categoria);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                //redirectToAction sirve para redireccionar hacia otra página 
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(Categoria categoria)
        {
            //UPDATE categoria SET nombre = 'categoria.nombre', descripcion = 'categoria.descripcion'
            //WHERE id_categoria = categoria.id_categoria

            db.Entry(categoria).State = EntityState.Modified;//forma para editar los registros
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            if(id != null)
            {
                var categoria = db.Categoria.Find(id);
                if(categoria != null)
                {
                    return View(categoria);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Delete(int id_categoria)
        {
            var categoria = db.Categoria.Find(id_categoria);
            if (categoria != null)
            {
                //Remove => DELETE FROM categoria WHERE id_categoria = 2
                db.Categoria.Remove(categoria);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

sistemaInventario/Controllers/MarcasController.cs
using sistemaInventario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sistemaInventario.Controllers
{
    public class MarcasController : Controller
    {
        private db_inventarioEntities db = new db_inventarioEntities();

        //método para accededr a crear marca
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Marca marca)
        {
            //insert into Marca('nombre','descripcion') values ('nombre','descripcion')
            db.Marca.Add(marca);
            //guarda cambios en la base de datos
            db.SaveChanges();
            return View();
        }
        //lista de marcas
        public ActionResult Index()
        {
            //lista de todas las marcas
            var marcas = db.Marca.ToList();//select * from marca
            return View(marcas);
        }
    }
}

sistemaInventario/Controllers/TipoUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sistemaInventario.Models;

namespace sistemaInventario.Controllers
{
    public class TipoUsuariosController : Controller
    {
        private db_inventarioEntities db = new db_inventarioEntities();

        // GET: TipoUsuarios
        public ActionResult Index()
        {
            return View(db.TipoUsuario.ToList());
        }

        // GET: TipoUsuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoUsuario tipoUsuario = db.TipoUsuario.Find(id);
            if (tipoUsuario == null)
            {
                return HttpNotFound();
            }
            return View(tipoUsuario);
        }

        // GET: TipoUsuarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoUsuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_tipo,nombre,descripcion")] TipoUsuario tipoUsuario)
        {
            if (ModelState.IsValid)
            {
                db.TipoUsuario.Add(tipoUsuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoUsuario);
        }

        // GET: TipoUsuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoUsuario tipoUsuario = db.TipoUsuario.Find(id);
            if (tipoUsuario == null)
            {
                return HttpNotFound();
            }
            return View(tipoUsuario);
        }

        // POST: TipoUsuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_tipo,nombre,descripcion")] TipoUsuario tipoUsuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoUsuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoUsuario);
        }

        // GET: TipoUsuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoUsuario tipoUsuario = db.TipoUsuario.Find(id);
            if (tipoUsuario == null)
            {
                return HttpNotFound();
            }
            return View(tipoUsuario);
        }

        // POST: TipoUsuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoUsuario tipoUsuario = db.TipoUsuario.Find(id);
            //verifica que el registro exista en la tabla usuario
            var usuario = db.Usuario.Where(u => u.id_tipousuario == tipoUsuario.id_tipo);
            if(usuario.Count() > 0)
            {
                //significa que el registro está siendo utilizado por usuario
                return RedirectToAction("Index");
            }
            db.TipoUsuario.Remove(tipoUsuario);
            db.SaveChanges(); 
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sistemaInventario/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sistemaInventario.Models;

namespace sistemaInventario.Controllers
{
    public class UsuariosController : Controller
    {
        private db_inventarioEntities db = new db_inventarioEntities();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string email, string password)
        {
            //verifica si las credenciales existen en la base de datos
            var user = db.Usuario.FirstOrDefault(u => u.email == email && u.pass == password);
            //si existen
            if(user != null)
            {
                //variable session sirve para almacenar datos de manera momentanea (se puede llamar en cualquier lugar del sistema)
                Session["Nombre"] = user.nombres + " " + user.apellidos;
                Session["idUser"] = user.id_usuario;
                Session["TipoUser"] = user.id_tipousuario;
                //redirecciona a la página de inicio
                return RedirectToAction("Index", "Productos");
            }
            return View();
        }
        public ActionResult LogOut()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            return RedirectToAction("Login");
        }
        // GET: Usuarios
        public ActionResult Index()
        {
            var usuario = db.Usuario.Include(u => u.TipoUsuario);
            return View(usuario.ToList());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            ViewBag.id_tipousuario = new SelectList(db.TipoUsuario, "id_tipo", "nombre");
            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_usuario,nombres,apellidos,rut,fono,email,pass,cargo,id_tipousuario")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_tipousuario = new SelectList(db.TipoUsuario, "id_tipo", "nombre", usuario.id_tipousuario);
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_tipousuario = new SelectList(db.TipoUsuario, "id_tipo", "nombre", usuario.id_tipousuario);
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_usuario,nombres,apellidos,rut,fono,email,pass,cargo,id_tipousuario")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_tipousuario = new SelectList(db.TipoUsuario, "id_tipo", "nombre", usuario.id_tipousuario);
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuario.Find(id);
            db.Usuario.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sistemaInventario/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Inventario</title>
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.easing.min.js"></script>
    <script src="~/Scripts/sb-admin-2.min.js"></script>


</head>
<body class="page-top">
    @if (Session["idUser"] != null)
    {
        <div id="wrapper">
            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="~\">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-laugh-wink"></i>
                    </div>
                    <div class="sidebar-brand-text mx-3">Sistema Inventario</div>
                </a>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->
                <li class="nav-item active">
                    <a class="nav-link" href="">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Inicio</span>
                    </a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Mantenerdores
                </div>
                @if (Session["TipoUser"].ToString() == "1")
                {
                    @Html.Partial("_MenuAdmin")
                }
                @if (Session["TipoUser"].ToString() == "3")
                {
                    @Html.Partial("_MenuUsuario")
                }
            </ul>
            <!-- End of Sidebar -->
            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                        <!-- Sidebar Toggle (Topbar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown no-arrow"><b>@Session["Nombre"]</b></li>
                            <div class="topbar-divider d-none d-sm-block"></div>
                            <li class="nav-item dropdown no-arrow">
                                <a href="@Url.Action("LogOut", "Usuarios")"><span class="fa fa-user-lock"> </span> Salir</a>
                            </li>
                        </ul>

                    </nav>
                    <!-- End of Topbar -->
                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                    <!-- /.container-fluid -->
                </div>

                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Derechos reservados &copy; </span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->
        </div>
    }
    else
    {
        Response.Redirect("~/");
    }
</body>
</html>

sistemaInventario/Views/Shared/_MenuAdmin.cshtml
  <!-- Nav Item Productos -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProducto"
       aria-expanded="true" aria-controls="collapseProducto">
        <i class="fas fa-fw fa-bars"></i>
        <span>Productos</span>
    </a>
    <div id="collapseProducto" class="collapse" aria-labelledby="headingProducto" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestión Productos:</h6>
            <a class="collapse-item" href="@Url.Action("Create", "Productos")">Crear Producto</a>
            <a class="collapse-item" href="@Url.Action("Index", "Productos")">Listado Productos</a>
        </div>
    </div>
</li>
<!-- Nav Item Marcas -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne"
       aria-expanded="true" aria-controls="collapseOne">
        <i class="fas fa-fw fa-cog"></i>
        <span>Marcas</span>
    </a>
    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestión Marcas:</h6>
            <a class="collapse-item" href="@Url.Action("Create", "Marcas")">Crear Marca</a>
            <a class="collapse-item" href="@Url.Action("Index", "Marcas")">Listado Marcas</a>
        </div>
    </div>
</li>
<!-- Nav Item Categorías -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCategorias"
       aria-expanded="true" aria-controls="collapseCategorias">
        <i class="fas fa-fw fa-wrench"></i>
        <span>Categorías</span>
    </a>
    <div id="collapseCategorias" class="collapse" aria-labelledby="headingCategorias"
         data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestión Categorías:</h6>
            <a class="collapse-item" href="@Url.Action("Create", "Categorias")">Crear Categoría</a>
            <a class="collapse-item" href="@Url.Action("Index", "Categorias")">Listado Categorías</a>
        </div>
    </div>
</li>
<!-- Nav Item Usuarios -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUsers"
       aria-expanded="true" aria-controls="collapseUsers">
        <i class="fas fa-fw fa-user"></i>
        <span>Usuarios</span>
    </a>
    <div id="collapseUsers" class="collapse" aria-labelledby="headingCategorias"
         data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestión Usuarios:</h6>
            <a class="collapse-item" href="@Url.Action("Create", "Usuarios")">Crear Usuarios</a>
            <a class="collapse-item" href="@Url.Action("Index", "Usuarios")">Listado Categorías</a>
            <a class="collapse-item" href="@Url.Action("Create", "TipoUsuarios")">Crear Tipo Usuario</a>
            <a class="collapse-item" href="@Url.Action("Index", "TipoUsuarios")">Listado Tipos usuarios</a>
        </div>
    </div>
</li>

sistemaInventario/Views/Shared/_MenuUsuario.cshtml
  <!-- Nav Item Ordenes Entrada -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProductoE"
       aria-expanded="true" aria-controls="collapseProductoE">
        <i class="fas fa-fw fa-car-side"></i>
        <span>Oredenes Entrada</span>
    </a>
    <div id="collapseProductoE" class="collapse" aria-labelledby="headingProducto" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestión:</h6>
            <a class="collapse-item" href="@Url.Action("OrdenEntrada", "OrdenEntradas")">Ingresar Productos</a>
            <a class="collapse-item" href="@Url.Action("HistorialEntradas", "OrdenEntradas")">Listado Productos Ingresados</a>
        </div>
    </div>
</li>