sistemaInventario/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleEntrada = new HashSet<DetalleEntrada>();
            this.DetalleSalida = new HashSet<DetalleSalida>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public int precio { get; set; }
        public string descripcion { get; set; }
        public int id_marca { get; set; }
        public int id_categoria { get; set; }
        public int id_proveedor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string foto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntrada> DetalleEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSalida> DetalleSalida { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}

sistemaInventario/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sistemaInventario.Models;

namespace sistemaInventario.Controllers
{
    public class ProductosController : Controller
    {
        private db_inventarioEntities db = new db_inventarioEntities();
        public ActionResult Create()
        {
            //sirve para llenar un select a través del helper Html.DropDownList
            ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "nombre");
            //select * from marca m order by m.nombre desc
            ViewBag.marca = new SelectList(db.Marca.OrderBy(m=>m.nombre), "id_marca", "nombre");
            ViewBag.proveedor = new SelectList(db.Proveedor, "id_proveedor", "nombre");
            return View();
        }
        [HttpPost]
        //HttpPostedFileBase permite recibir un archivo enviado por post
        public ActionResult Create(Producto producto,  HttpPostedFileBase imagen)
        {
            if(imagen != null)
            {
                //capturar el extensión de la imagen 
                string extension = Path.GetExtension(imagen.FileName);
                //string nombreArchivo = Path.GetFileName(imagen.FileName); forma de capturar el nombre
                string nombreArchivo = producto.codigo + extension;//se combina el nuevo nombre con la extensión del archivo
                //ruta de donde se guardará el archivo
                string ruta = Path.Combine(Server.MapPath("~/Imagenes/"), nombreArchivo);
                imagen.SaveAs(ruta);// el archivo.SaveAs(ruta) permita copiar el archivo subido a la carpeta de destino 
                producto.foto = "~/Imagenes/" + nombreArchivo;
            }

            db.Producto.Add(producto);
            db.SaveChanges();

            //se vuelven a cargar la lista con datos
            ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "nombre");
            ViewBag.marca = new SelectList(db.Marca.OrderBy(m => m.nombre), "id_marca", "nombre");
            ViewBag.proveedor = new SelectList(db.Proveedor, "id_proveedor", "nombre");
            return Json("Ok");
        }
        //método para verificar si el código del producto ya esta ingresado
        [HttpPost]
        public ActionResult CodigoExiste(string codigo)
        {
            //pregunta si el string es distinto de nullo vacío
            if (!string.IsNullOrEmpty(codigo))
            {
                //select * from producto p where LOWER(p.codigo) = LOWER(codigo)
                var q = db.Producto.FirstOrDefault(p=>p.codigo.ToLower().Equals(codigo.ToLower()));
                if(q != null)
                {
                    string nombre = q.nombre;//devuelve el nombre del producto cuyo código esta ingresado
                    return Json(nombre);
                }
            }
            return Json("");
        }
        public ActionResult Index()
        {
            //viewbag para los select
            ViewBag.proveedor = new SelectList(db.Proveedor, "id_proveedor", "nombre");
            ViewBag.marca = new SelectList(db.Marca, "id_marca", "nombre");
            ViewBag.categoria = new SelectList(db.Categoria, "id_categoria", "nombre");
            return View();
        }

        public ActionResult Edit(int id)
        {
            //consulta el detalla del producto en base al id 
            var producto = db.Producto.Find(id);
            if(producto != null)
            {
                ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "nombre", producto.id_categoria);
                ViewBag.id_marca = new SelectList(db.Marca, "id_marca", "nombre", producto.id_marca);
                ViewBag.id_proveedor = new SelectList(db.Proveedor, "id_proveedor", "nombre", producto.id_proveedor);
                return PartialView("_Edit",producto);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Edit(Producto producto)
        {
            db.Entry(producto).State = EntityState.Modified;
            db.SaveChanges();
            return Json("ok");
        }
        //buscar según filtros
        public ActionResult ListarProductos(int? proveedor, int? marca, int? categoria)
        {
            //retornar todos los productos
            var productos = db.Producto.ToList();
            //verifica 
            if (proveedor != null)
                productos = productos.Where(p => p.id_proveedor == proveedor).ToList();

            if (marca != null)
                productos = productos.Where(p => p.id_marca == marca).ToList();

            if (categoria != null)
                productos = productos.Where(p => p.id_categoria == categoria).ToList();

            return PartialView("_ListarProductos",productos);
        }
    }
}

sistemaInventario/Views/Productos/Create.cshtml
@{
    ViewBag.Title = "Crear Producto";
}

<div class="card mb-4">
    <div class="card-header">
        Crear Producto
    </div>

    <div class="card-body">
            <div class="form-group row">
                <label class="col-2">Categoría: </label>
                <div class="col-10">
                    @Html.DropDownList("id_categoria", null, "Seleccione categoría", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Marca: </label>
                <div class="col-10">
                    <!--Html.DropDownList es un helper para mostrar los select con un ViewBag-->
                    @Html.DropDownList("marca", null, "Seleccione una marca", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Proveedor: </label>
                <div class="col-10">
                    @Html.DropDownList("proveedor", null, "Seleccione proveedor", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Nombre: </label>
                <div class="col-10">
                    <input type="text" name="nombre" id="nombre" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Código: </label>
                <div class="col-10">
                    <input type="text" name="codigo" id="codigo" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Precio: </label>
                <div class="col-10">
                    <input type="text" name="precio" id="precio" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Descripción: </label>
                <div class="col-10">
                    <textarea name="descripcion" id="descripcion" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Foto: </label>
                <div class="col-10">
                    <input type="file" id="imagen" name="imagen" class="form-control" accept="image/jpg,image/png,image/jpeg" />
                </div>
            </div>
            <div class="text-center">
                <input type="submit" id="btnEnviar" value="Guardar" class="btn btn-lg btn-success" />
            </div>
    </div>
</div>
<script src="~/Scripts/swal.min.js"></script>
<script>
    $('#btnEnviar').click(function (e) {
        let error = '';
        if (!$('#id_categoria').val()) {
            error = 'Debe seleccionar categoría del producto \n';
        }
        if (!$('#marca').val()) {
            error += 'Debe seleccionar marca del producto \n';
        }
        if (!$('#proveedor').val()) {
            error += 'Debe seleccionar proveedor del producto \n';
        }
        if ($('#nombre').val().trim() == '') {
            error += 'Debe ingresar nombre del producto \n';
        }
        if ($('#codigo').val().trim() == '') {
            error += 'Debe ingresar código del producto \n';
        }
        if ($('#precio').val().trim() == '') {
            error += 'Debe ingresar precio del producto \n';
        }
        if (error != '') {
            e.preventDefault();
            swal('Error validación', error, 'warning');
        } else {
            let producto = new FormData();//permite enviar datos 
            producto.append('nombre', $('#nombre').val());
            producto.append('codigo', $('#codigo').val());
            producto.append('precio', $('#precio').val());
            if ($('#descripcion').val().trim() != '')
                producto.append('descripcion', $('#descripcion').val());
            producto.append('id_marca', $('#marca').val());
            producto.append('id_proveedor', $('#proveedor').val());
            producto.append('id_categoria', $('#id_categoria').val());
            if($('#imagen').val() != '')
                producto.append('imagen', $('#imagen')[0].files[0]);
            console.log($('#imagen')[0].files[0]);
                $.ajax({
                type: 'POST',
                url: '@Url.Action("Create")',
                data: producto,
                contentType: false,
                processData: false,
                success: function (result) {
                    if (result == 'Ok') {
                        swal({
                            title: 'Guardado con éxito!!!',
                            text: 'Los datos se han guardado',
                            icon: 'success',
                            button: 'Confirmar',
                            closeOnClickOutside: true
                        }).then(function (isConfirm) {
                            if (isConfirm) {
                                location.reload();
                            }
                        });
                    }
                }
            });
        }
    });
    //se activa la función cuando pierde el focus del input código
    $('#codigo').blur(function () {
        if ($('#codigo').val().trim() != '') {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CodigoExiste")',
                data: '{codigo:' + JSON.stringify($('#codigo').val().trim()) + '}',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (result) {
                    if (result != '') {
                        swal('Error', 'El código ya existe para el producto: ' + result, 'warning');
                        $('#codigo').val('');
                    }
                }
            });
        }
    });
</script>

sistemaInventario/Views/Productos/Index.cshtml
@model IEnumerable<sistemaInventario.Models.Producto>
@{
    ViewBag.Title = "Index";
}



<div class="card mb-4">
    <div class="card-header">
        Listado de Productos
    </div>
    <div class="card-body">
        <div class="form-group row">
            <label class="col-1">Proveedor</label>
            <div class="col-2">
                @Html.DropDownList("proveedor", null, "Todos", htmlAttributes: new { @class = "form-control" })
            </div>
            <label class="col-1">Marca</label>
            <div class="col-2">
                @Html.DropDownList("marca", null, "Todas", htmlAttributes: new { @class = "form-control" })
            </div>
            <label class="col-1">Categoría</label>
            <div class="col-2">
                @Html.DropDownList("categoria", null, "Todas", htmlAttributes: new { @class = "form-control" })
            </div>
            <button class="btn btn-success" id="buscar">
                Buscar
            </button>
        </div>
        <hr />
        <div class="table-responsive" id="tablaProductos"></div>
    </div>
</div>


<script>
    ///método que envía los filtros al contralador y muesta la tabla con los filtros
    $('#buscar').click(function () {
        cargarTabla();
    });
    function cargarTabla() {
        let datos = '?proveedor=' + $('#proveedor').val() + '&marca=' + $('#marca').val() + '&categoria='+ $('#categoria').val();
        $.get('@Url.Action("ListarProductos")' + datos, function (productos) {
            $('#tablaProductos').html(productos);
        });
    }
</script>

sistemaInventario/Views/Productos/_Edit.cshtml
@model sistemaInventario.Models.Producto

<div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Editar Producto</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <div class="form-group row">
                <input type="hidden" name="id_producto" id="id_producto" value="@Model.id_producto" />
                <!-- @Html.HiddenFor(p=>p.id_producto) helper razor para ocultar un input-->
                <label class="col-2">Categoría:</label>
                <div class="col-10">
                    @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Marca:</label>
                <div class="col-10">
                    @Html.DropDownList("id_marca", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Proveedor:</label>
                <div class="col-10">
                    @Html.DropDownList("id_proveedor", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Nombre:</label>
                <div class="col-10">
                    <input type="text" name="nombre" id="nombre" value="@Model.nombre" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Código:</label>
                <div class="col-10">
                    <input type="text" name="codigo" id="codigo" value="@Model.codigo" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Precio:</label>
                <div class="col-10">
                    <input type="text" name="precio" id="precio" value="@Model.precio" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2">Descripción:</label>
                <div class="col-10">
                    <input type="text" name="descripcion" id="descripcion" value="@Model.descripcion" class="form-control" />
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" id="btnCerrar" data-dismiss="modal">Cerrar</button>
            <input type="button" id="btnEditar" value="Editar" class="btn btn-success" />
        </div>
    </div>
</div>
<script src="~/Scripts/swal.min.js"></script>
<script>
    $('#btnEditar').click(function () {
        //validación
        let error = '';
        if ($('#nombre').val().trim() == '') {
            error += 'Debe ingresar nombre del producto \n';
        }
        if ($('#codigo').val().trim() == '') {
            error += 'Debe ingresar código del producto \n';
        }
        if ($('#precio').val().trim() == '') {
            error += 'Debe ingresar precio del producto \n';
        }
        if (error != '') {
            swal('Error validación', error, 'warning');
        }
        else {
            //construir el objeto a enviar al controlador
            const producto = {
                id_producto: $('#id_producto').val(),
                id_categoria: $('#id_categoria').val(),
                id_marca: $('#id_marca').val(),
                id_proveedor: $('#id_proveedor').val(),
                nombre: $('#nombre').val().trim(),
                codigo: $('#codigo').val().trim(),
                precio: $('#precio').val(),
                descripcion: $('#descripcion').val().trim()
            }
            //se envia por ajax y método post
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Edit")',
                data: '{producto:' + JSON.stringify(producto) + '}',
                dataType: 'json',
                contentType: 'application/json; chartset=utf-8',
                success: function (respuesta) {
                    //si la respuesta es igual a ok realiza actualización
                    if (respuesta === 'ok') {
                        $('#modaEdit').modal('hide');//se cierra el modal popup
                        swal({
                            title: 'Modificar producto',
                            text: 'Los datos han sido modificados con éxito!!!',
                            icon: 'success',
                            closeOnClickOutside: false,
                        }).then(function (value) {
                            if (value) {
                                //location.reload(); //sirve para recargar la página
                                cargarTabla();
                            }
                        });
                    }
                }
            });
        }
    });

</script>

sistemaInventario/Views/Productos/_ListarProductos.cshtml
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Proveedor</th>
            <th>Categoría</th>
            <th>Marca</th>
            <th>Producto</th>
            <th>Código</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Descripción</th>
            <th>Foto</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Proveedor.nombre</td>
                <td>@item.Categoria.nombre</td>
                <td>@item.Marca.nombre</td>
                <td>@item.nombre</td>
                <td>@item.codigo</td>
                <td>@item.precio.ToString("C")</td>
                <td>@item.cantidad</td>
                <td>@item.descripcion</td>
                <td>
                    @if (item.foto != null)
                    {
                         <img src="@Url.Content(item.foto)"  style="height:200px"/>
                    }
                </td>
                <td>
                    <button class="btn btn-warning" data-toggle="modal" data-target="#modalEdit"
                            data-url="@Url.Action("Edit","Productos", new { id = item.id_producto})">
                        Editar
                    </button>
                    <a href="/Productos/Delete/@item.id_producto" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="modalEdit">
</div>
<script>
    $('.btn-warning').click(function () {
        let url = $(this).data('url');//Productos/Edit/1
        //permite acceder al controdalor y a un acción (Porudctos/Edit)
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').show();
        });
    });
</script>